name: "Examples"

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to checkout"
        required: false
        type: string
        default: ${{ github.repository }}

      ref:
        description: "Git ref to checkout"
        required: false
        type: string

      system:
        description: "System to run examples on"
        required: true
        type: string

      runs-on:
        description: "Runner to use"
        required: true
        type: string

      nixpkgs-input:
        description: "An optional nixpkgs input to test against"
        required: false
        type: string

jobs:
  generate-examples:
    runs-on: [self-hosted, linux]

    outputs:
      examples: ${{ steps.set-examples.outputs.examples }}

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH

      - name: Fetch examples to run
        id: set-examples
        # Get test metadata filtered for current system
        run: |
          set -euxo pipefail
          examples=$(devenv-run-tests generate-json examples)
          echo "examples=$examples" >> $GITHUB_OUTPUT

  examples:
    needs: [generate-examples]
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: ${{ matrix.example.name }} (${{ inputs.system }})

    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJSON(needs.generate-examples.outputs.examples) }}

    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build devenv
        run: |
          path=$(nix build -L --print-out-paths)
          echo "$path/bin" >> $GITHUB_PATH

      - name: Run examples
        env:
          NIXPKGS_INPUT: ${{ inputs.nixpkgs-input }}
        run: |
          args=()
          if [ -n "$NIXPKGS_INPUT" ]; then
            args+=(--override-input nixpkgs "$NIXPKGS_INPUT")
          fi

          devenv-run-tests "${args[@]}" run --only ${{ matrix.example.name }} examples
